config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  apipie
  get 'home/index'

  get "/pages/:page" => "pages#show"
  get "/logout" => "pages#logout"


  # Auth0
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"


  # BoController
  resources :bo_events,
            :categories,
            :partners,
            :prize_contents,
            :bo_challenges,
            :bo_prizes

  namespace :backoffice do
    resources :partners
  end

  namespace :api, defaults: {format: :json} do

    get 'request/token' => 'authentication#send_login_token'
    get 'login' => 'authentication#login'
    post 'register' => 'authentication#register'

    resources :styles,
              :followings,
              :wows,
              :comments,
              :rankings,
              :deals,
              :teams,
              :memberships,
              :team_requests,
              :awards,
              :points
    namespace :challenges do
      resources :single_challenges, path: 'singles'
      resources :team_challenges, path: 'teams'
      resources :styles
    end

    resources :users do
      resources :styles
      resources :memberships
      resources :awards
    end

    resources :teams do
      resources :memberships
      resources :team_requests
    end
  end

end

app/models/award.rb
class Award < ApplicationRecord
  include Filterable

  belongs_to :partner, optional: true
  belongs_to :challenge, optional: true
  belongs_to :style, optional: true


  delegate :user, :to => :style, :allow_nil => true

  scope :user_id, ->(user_id) {includes(:style).where(styles: {user_id: user_id})}
end

app/models/bo_user.rb
class BoUser
  include ActiveModel::Model

  attr_accessor :name, :nickname, :email

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :challenges
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  include Filterable
  before_save :set_state, unless: :state

  scope :single_challenges, -> {where(type: 'SingleChallenge')}

  belongs_to :category
  has_many :awards
  has_many :styles
  belongs_to :participation_reward

  def set_state
    new_state = check_state
    puts title + ', Old State: ' + state + ', New State: ' + new_state if state
    self.state = new_state
  end

  def check_state
    if start > Time.now
      'created'
    elsif (start..self.end).cover?(Time.now)
      'active'
    else
      'finished'
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :style, counter_cache: :count_of_comments
  belongs_to :user
  has_many :user_actions

end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :partner
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :following_user,
             class_name: 'User', foreign_key: 'following_user_id'
  belongs_to :followed_user,
             class_name: 'User', foreign_key: 'followed_user_id'

  has_many :user_actions

end

app/models/membership.rb
class Membership < ApplicationRecord
  include Filterable

  belongs_to :team, optional: true
  belongs_to :user, optional: true

  scope :team_id, -> (team_id) {where team_id: team_id}
  scope :user_id, -> (user_id) {where user_id: user_id}
  scope :role, -> (role) {where role: role}


end

app/models/partner.rb
class Partner < ApplicationRecord
  has_attached_file :image, styles: {
      thumb: '50x50>',
      square: '200x200#',
      medium: '300x300>'
  }
  has_many :awards


  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/style.rb
class Style < ApplicationRecord
  include Filterable

  belongs_to :user
  belongs_to :challenge
  has_one :award
  has_many :comments

  has_many :wows
  has_many :wowing_users, through: :wows, source: :user

  has_many :user_actions

  scope :id, -> (id) {where id: id}
  scope :challenge_id, -> (challenge_id) {where challenge_id: challenge_id}
  scope :user_id, -> (user_id) {where user_id: user_id}

end

app/models/team.rb
class Team < ApplicationRecord
  include Filterable
  after_create :create_ownership

  belongs_to :user
  has_many :membership, dependent: :destroy
  has_many :team_requests, dependent: :destroy

  def create_ownership
    membership = Membership.new(user_id: user_id, team_id: id, role: 'owner')
    self.membership << membership
  end
end

app/models/team_challenge.rb
class TeamChallenge < Challenge
  include Filterable

  has_many :team_challenge_stages, foreign_key: 'winning_team_id', class_name: 'TeamChallengeStage'

end

app/models/team_request.rb
class TeamRequest < ApplicationRecord
  include Filterable

  before_save :check_team
  after_save :create_membership

  belongs_to :user
  belongs_to :team

  has_many :membership, through: :team

  def check_team
    self.status = 'accepted' if team.public?
  end

  def create_membership
    Membership.new(user_id: user.id, team_id: team.id, role: 'member').save if status == 'accepted'
  end

  scope :team_id, -> (team_id) {where team_id: team_id}

end

app/models/user.rb
class User < ApplicationRecord
  include Filterable
  has_secure_token :auth_token
  after_create :set_score

  validates :email, :username, uniqueness: true, presence: true

  has_many :style
  has_many :comment
  has_many :user_actions
  has_many :membership
  has_many :team

  has_many :given_wows,
           foreign_key: 'user_id', class_name: 'Wow'

  has_many :followings_info,
           foreign_key: 'followed_user_id', class_name: 'Following'
  has_many :followers_info, foreign_key: 'following_user_id', class_name: 'Following'

  has_many :followings, through: :followings_info, source: :following_user
  has_many :followers, through: :followers_info, source: :followed_user

  has_many :challenge, through: :style

  has_many :awards, through: :style

  has_one :point

  scope :username, ->(username) {where 'lower(username) LIKE lower(?) ', "%#{username}%"}

  def set_auth_info(_params)
    puts title + ', Old State: ' + state if state
    self.state = check_state
    puts title + ', New State: ' + state
  end

  def self.find_user_by(value)
    where(['username = :value OR email = :value', {value: value}]).first
  end

  def generate_login_token
    self.login_token = SecureRandom.hex(3)
    self.token_generated = Time.now.utc
    save!
  end

  def login_token_expired?
    Time.now.utc > (token_generated + token_validity)
  end

  def token_validity
    2.hours
  end

  def set_score
    point = Point.create(user: self)
  end

end

app/models/user_action.rb
class UserAction < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :comment, optional: true
  belongs_to :style, optional: true
  belongs_to :wow, optional: true
  belongs_to :following, optional: true

end

app/models/wow.rb
class Wow < ApplicationRecord
  belongs_to :user
  belongs_to :style, counter_cache: :count_of_wows

  has_many :user_actions
end

app/helpers/auth0_helper.rb
module Auth0Helper
end

app/helpers/session_helper.rb
module SessionHelper
  def get_state
    state = SecureRandom.hex(24)
    session['omniauth.state'] = state

    state
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SengaaBackend</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

<small>Eingeloggt als <%= @boUser.nickname %></small>

<ul>
  <li><a href="home">Home</a></li>
  <li><a href="challenges">Challenges</a></li>
  <li><a href="partners">Partners & Prize Contents</a></li>
  <li><a href="categories">Categories</a></li>

  <li style="float:right"><a class="active" href="/logout">Logout</a></li>

</ul>

<div class="content">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/categories.html.slim
h1 Categories
div.card {style = "vertical-align:top"}
  p Add Category
  = form_for :category, url: categories_path do |f|
    div.field
      = f.label :name
      br
      = f.text_field :name
    div.field
      = f.submit

div class = "card"
  div style="overflow-x:auto;"
  - if @categories.present?
    = will_paginate @categories, :param_name => 'categories_page'
    table
      thead
        tr
          th Id
          th Category Name
      tbody
        - @categories.each do |category|
          tr
            td = category.id
            td = category.name
            /td
              /  = link_to "Delete", {:controller => "categories", :action => 'destroy', :id => category.id}, :method => :delete, class: "btn btn-default", data: { confirm: 'Are you sure you want to reset the indexes?' }
  - else
    p No category in the database

app/views/pages/challenges.html.slim
h1 Challenges

div.card
  p Add Challenge
  = form_for :challenge, url: bo_challenges_path do |f|
    div.field
      = f.label :title
      br
      = f.text_field :title
    div.field
      = f.label :description
      br
      = f.text_field :description
    div.field
      = f.label :category
      br
      = f.collection_select(:category_id, Category.all, :id, :name, include_blank: "Select Challenge Category")
    div.field
      = f.label :start
      br
      = f.date_select :start
      = f.time_select :start, :ignore_date => true
    div.field
      = f.label :end
      br
      = f.date_select :end
      = f.time_select :end, :ignore_date => true

    div.field
      = f.label :gender
      br
        = f.select :gender, Challenge.genders.keys
    div.field
    = f.submit

br

div class = "card"
  div style="overflow-x:auto;"
  - if @challenges.present?
    = will_paginate @challenges, :param_name => 'challenges_page'
    table
      thead
        tr
          th Id
          th Title
          th Description
          th State
          th Category
          th Start
          th End
          th Gender
          th Prizes
      tbody
        - @challenges.each do |challenge|
          tr
            td
              = challenge.id
            td
              = challenge.title
            td
              = challenge.description
            td
              = challenge.state
            /img src =challenge.challenge_prize.partner.image.url(:thumb)
            td
              = challenge.category.name
            td
              = challenge.start
            td
              = challenge.end
            td
              = challenge.gender
            td
              - challenge.prizes.each do |p|
                div  #{p.position} #{p.prize_content.title}
            td
              = form_for :prize, url: bo_prizes_path do |f|
                div.field
                  = f.hidden_field :challenge_id, :value => challenge.id
                  = f.collection_select(:prize_content_id, PrizeContent.all, :id, :title, include_blank: "Select PrizeContent")
                div.field
                  = f.number_field :position, :class => 'text_field', :step => 1, :min => 0
                div.field
                  = f.submit
  - else
    p No challenge in the database

app/views/pages/home.html.slim
h1 sengaa Dashboard
p In the making...

app/views/pages/partners.html.slim
h1 Partners & Prize Contents

div.card {style = "vertical-align:top"}
  p Add a partner
  = form_for :partner, url: partners_path do |f|
    div.field
      = f.label :name
      br
      = f.text_field :name
    div.field
      = f.label :url
      br
      = f.text_field :url
    div.field
      = f.label 'Choose an image'
      br
      = f.file_field :image
    div.field
      = f.submit

div class = "card"
  p Add PrizeContent
  = form_for :prize, url: prize_contents_path do |f|
    div.field
      = f.label 'Type'
      br
      = f.collection_select(:partner_id, Partner.all, :id, :name, include_blank: "Select Partner")
    div.field
      = f.label :title
      br
      = f.text_field :title
    div.field
      = f.label :description
      br
      = f.text_field :description
    div.field
      = f.label :code
      br
      = f.text_field :code
    div.field
      = f.submit

br

div.card
  div style="overflow-x:auto;"
  - if @partners.present?
    = will_paginate @partners, :param_name => 'partners_page'
    table
      thead
        tr
          th Id
          th Name
          th Image
      tbody
        - @partners.each do |partner|
          tr
            td
              = partner.id
            td
              = partner.name
            td
              img src =partner.image.url(:thumb)
            td
              = link_to "Delete", {:controller => "partners", :action => 'destroy', :id => partner.id}, :method => :delete, class: "btn btn-default", data: {confirm: 'Are you sure?'}
  - else
    p No partner in the database
br

div.card
  div style="overflow-x:auto;"
  - if @prizeContents.present?
    = will_paginate @prizeContents, :param_name => 'prize_content_page'
    table
      thead
        tr
          th Id
          th Title
          th Partner
          th Description
          th Code
      tbody
        - @prizeContents.each do |prizeContent|
          tr
            td
              = prizeContent.id
            td
              = prizeContent.title
            td
              = prizeContent.partner.name
            td
              = prizeContent.description
            td
              = prizeContent.code
            td
              = link_to "Delete", {:controller => "prize_contents", :action => 'destroy', :id => prizeContent.id}, :method => :delete, class: "btn btn-default", data: {confirm: 'Are you sure?'}
  - else
    p No prize in the database